version: '3'
services:

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # students-service:
  #   build: "./students-service"
  #   ports: 
  #     - "4001:4001"
  #   command: yarn start
  #   depends_on:
  #     - postgres
  
  # student-admin:
  #   build: "./student-admin"
  #   ports: 
  #     - "3000:3000"
  #   command: yarn start
  #   depends_on:
  #     - postgres
  #     - students-service 
